-- CreateTable
CREATE TABLE "Safra" (
    "ID" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "DATA_INICIO" TEXT NOT NULL,
    "DATA_FINALIZACAO" TEXT NOT NULL,
    "ABREVIACAO" TEXT NOT NULL,
    "DATA_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATA_ATUALIZACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Safra_pkey" PRIMARY KEY ("ID")
);
